pretrained_model_name_or_path: Qwen/Qwen-Image-Edit-2511
data_config:
  train_batch_size: 1
  num_workers: 8
  img_size: 1024
  caption_dropout_rate: 0.1
  img_dir: /home/work/tmp/trainer/dataset_ready/ready/images
  control_dir: /home/work/tmp/trainer/dataset_ready/ready/control
  random_ratio: false
  caption_type: txt
report_to: null
train_batch_size: 1
output_dir: ./lora_saves_with_iou
max_train_steps: 200
learning_rate: 2e-4
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 200
checkpoints_total_limit: 100
tracker_project_name: lora_sim2real_1024
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
rank: 4
precompute_text_embeddings: true
precompute_image_embeddings: true
quantize: false
adam8bit: false
save_cache_on_disk: false
use_iou_reward: true
loss_log_path: loss_with_iou.csv
